 select code, 
    sum( age_ranges_age_under_1 + age_ranges_age_2 + age_ranges_age_3 + age_ranges_age_4 ) as age_u5, 
    sum( age_ranges_age_5 + age_ranges_age_6 + age_ranges_age_7 + age_ranges_age_8 + age_ranges_age_9 + age_ranges_age_10 ) as age_5_10, 
    sum( age_ranges_age_11 + age_ranges_age_12 + age_ranges_age_13 + age_ranges_age_14 + age_ranges_age_15 ) as age_11_15, 
    sum( age_ranges_age_16 + age_ranges_age_17 + age_ranges_age_18 + age_ranges_age_19 + age_ranges_age_20 + age_ranges_age_21 + age_ranges_age_22 + age_ranges_age_23 + age_ranges_age_24 ) as age_16_24, 
    sum( age_ranges_age_25 + age_ranges_age_26 + age_ranges_age_27 + age_ranges_age_28 + age_ranges_age_29 + age_ranges_age_30 + age_ranges_age_31 + age_ranges_age_32 + age_ranges_age_33 + age_ranges_age_34 ) as age_25_34, 
    sum( age_ranges_age_35 + age_ranges_age_36 + age_ranges_age_37 + age_ranges_age_38 + age_ranges_age_39 + age_ranges_age_40 + age_ranges_age_41 + age_ranges_age_42 + age_ranges_age_43 + age_ranges_age_44 ) as age_35_44, 
    sum( age_ranges_age_45 + age_ranges_age_46 + age_ranges_age_47 + age_ranges_age_48 + age_ranges_age_49 + age_ranges_age_50 + age_ranges_age_51 + age_ranges_age_52 + age_ranges_age_53 + age_ranges_age_54 ) as age_45_54, 
    sum( age_ranges_age_55 + age_ranges_age_56 + age_ranges_age_57 + age_ranges_age_58 + age_ranges_age_59 ) as age_55_59, 
    sum( age_ranges_age_60 + age_ranges_age_61 + age_ranges_age_62 + age_ranges_age_63 + age_ranges_age_64 ) as age_60_64, 
    sum( age_ranges_age_65 + age_ranges_age_66 + age_ranges_age_67 + age_ranges_age_68 + age_ranges_age_69 + age_ranges_age_70 + age_ranges_age_71 + age_ranges_age_72 + age_ranges_age_73 + age_ranges_age_74 ) as age_65_74, 
    sum( age_ranges_age_75 + age_ranges_age_76 + age_ranges_age_77 + age_ranges_age_78 + age_ranges_age_79 + age_ranges_age_80 + age_ranges_age_81 + age_ranges_age_82 + age_ranges_age_83 + age_ranges_age_84 + 
         age_ranges_age_85 + age_ranges_age_86 + age_ranges_age_87 + age_ranges_age_88 + age_ranges_age_89 + age_ranges_age_90 + age_ranges_age_91 + age_ranges_age_92 + age_ranges_age_93 + age_ranges_age_94 + 
         age_ranges_age_95 + age_ranges_age_96 + age_ranges_age_97 + age_ranges_age_98 + age_ranges_age_99 + age_ranges_age_100_and_over ) as age_75_plus ,
    sum(genders_males ) as males, sum( genders_females ) as females ,
    sum( ethgrp_white+ethgrp_other ) as s_ethgrp_white, 
    sum( ethgrp_mixed ) as ethgrp_mixed, 
    sum( ethgrp_asian ) as ethgrp_asian, 
    sum( ethgrp_black ) as ethgrp_black, 
    sum( Tenure_Owned_Owned_Outright ) as owned_outright, 
    sum( Tenure_Owned_Owned_With_A_Mortgage_Or_Loan + Tenure_Shared_Ownership_Part_Owned_And_Part_Rented ) as mortgaged, 
    sum( Tenure_Social_Rented_Total) as social_rented, 
    sum( Tenure_Private_Rented_Total + Tenure_Living_Rent_Free ) as private_rented_or_rent_free,
    sum( number_of_rooms_1_room ) as rooms_1, 
    sum( number_of_rooms_2_rooms + number_of_rooms_3_rooms ) as rooms_2_3, 
    sum( number_of_rooms_4_rooms + number_of_rooms_5_rooms ) as rooms_4_5, 
    sum( number_of_rooms_6_rooms + number_of_rooms_7_rooms + number_of_rooms_8_rooms + number_of_rooms_9_or_more_rooms ) as rooms_6_plus,
    sum( number_of_rooms_1_room ) as s_1_room, 
    sum( number_of_rooms_2_rooms ) as s_2_room, 
    sum( number_of_rooms_3_rooms ) as s_3_room, 
    sum( number_of_rooms_4_rooms ) as s_4_room, 
    sum( number_of_rooms_5_rooms ) as s_5_room, 
    sum( number_of_rooms_6_rooms ) as s_6_room, 
    sum( number_of_rooms_7_rooms ) as s_7_room, 
    sum( number_of_rooms_8_rooms ) as s_8_room, 
    sum( number_of_rooms_9_or_more_rooms ) as s_9_room,
    sum( occupation_1_managers_directors_and_senior_officials ) as s_1_managers_directors_and_senior_officials , 
    sum( occupation_2_professional_occupations ) as s_2_professional_occupations , 
    sum( occupation_3_associate_professional_and_technical_occupations ) as s_3_associate_professional_and_technical_occupations , 
    sum( occupation_4_administrative_and_secretarial_occupations ) as s_4_administrative_and_secretarial_occupations , 
    sum( occupation_5_skilled_trades_occupations ) as s_5_skilled_trades_occupations , 
    sum( occupation_6_caring_leisure_and_other_service_occupations ) as s_6_caring_leisure_and_other_service_occupations , 
    sum( occupation_7_sales_and_customer_service_occupations ) as s_7_sales_and_customer_service_occupations , 
    sum( occupation_8_process_plant_and_machine_operatives ) as s_8_process_plant_and_machine_operatives , 
    sum( occupation_9_elementary_occupations ) as s_9_elementary_occupation,
    sum( occupation_1_managers_directors_and_senior_officials + occupation_2_professional_occupations + occupation_3_associate_professional_and_technical_occupations + 
         occupation_4_administrative_and_secretarial_occupations ) as white_collar, 
    sum( occupation_5_skilled_trades_occupations + occupation_6_caring_leisure_and_other_service_occupations + occupation_7_sales_and_customer_service_occupations + 
         occupation_8_process_plant_and_machine_operatives + occupation_9_elementary_occupations ) as blue_collar  
from target_candidates where edition =  1 and code in ( '0910', '1011')  group by code order by code;

