with Base_Model_Types; 
with RAW_FRS;
with Weighting_Commons;
with Ada.Calendar;
with Data_Constants;

package LA_Reweighter is
   
   use Base_Model_Types;
   use Weighting_Commons;
     
   type Local_Authorities is (
      uacounty09_darlington,
      uacounty09_county_durham,
      uacounty09_hartlepool,
      uacounty09_middlesbrough,
      uacounty09_northumberland,
      uacounty09_redcar_and_cleveland,
      uacounty09_stockton_on_tees,
      uacounty09_gateshead,
      uacounty09_newcastle_upon_tyne,
      uacounty09_north_tyneside,
      uacounty09_south_tyneside,
      uacounty09_sunderland,
      uacounty09_blackburn_with_darwen,
      uacounty09_blackpool,
      uacounty09_cheshire_east,
      uacounty09_cheshire_west_and_chester,
      uacounty09_halton,
      uacounty09_warrington,
      uacounty09_cumbria,
      uacounty09_bolton,
      uacounty09_bury,
      uacounty09_manchester,
      uacounty09_oldham,
      uacounty09_rochdale,
      uacounty09_salford,
      uacounty09_stockport,
      uacounty09_tameside,
      uacounty09_trafford,
      uacounty09_wigan,
      uacounty09_lancashire,
      uacounty09_knowsley,
      uacounty09_liverpool,
      uacounty09_sefton,
      uacounty09_st_helens,
      uacounty09_wirral,
      uacounty09_east_riding_of_yorkshire,
      uacounty09_kingston_upon_hull_city_of,
      uacounty09_north_east_lincolnshire,
      uacounty09_north_lincolnshire,
      uacounty09_york,
      uacounty09_north_yorkshire,
      uacounty09_barnsley,
      uacounty09_doncaster,
      uacounty09_rotherham,
      uacounty09_sheffield,
      uacounty09_bradford,
      uacounty09_calderdale,
      uacounty09_kirklees,
      uacounty09_leeds,
      uacounty09_wakefield,
      uacounty09_derby,
      uacounty09_leicester,
      uacounty09_nottingham,
      uacounty09_rutland,
      uacounty09_derbyshire,
      uacounty09_leicestershire,
      uacounty09_lincolnshire,
      uacounty09_northamptonshire,
      uacounty09_nottinghamshire,
      uacounty09_herefordshire_county_of,
      uacounty09_shropshire,
      uacounty09_stoke_on_trent,
      uacounty09_telford_and_wrekin,
      uacounty09_staffordshire,
      uacounty09_warwickshire,
      uacounty09_birmingham,
      uacounty09_coventry,
      uacounty09_dudley,
      uacounty09_sandwell,
      uacounty09_solihull,
      uacounty09_walsall,
      uacounty09_wolverhampton,
      uacounty09_worcestershire,
      uacounty09_bedford,
      uacounty09_central_bedfordshire,
      uacounty09_luton,
      uacounty09_peterborough,
      uacounty09_southend_on_sea,
      uacounty09_thurrock,
      uacounty09_cambridgeshire,
      uacounty09_essex,
      uacounty09_hertfordshire,
      uacounty09_norfolk,
      uacounty09_suffolk,
      uacounty09_camden,
      uacounty09_city_of_london,
      uacounty09_hackney,
      uacounty09_hammersmith_and_fulham,
      uacounty09_haringey,
      uacounty09_islington,
      uacounty09_kensington_and_chelsea,
      uacounty09_lambeth,
      uacounty09_lewisham,
      uacounty09_newham,
      uacounty09_southwark,
      uacounty09_tower_hamlets,
      uacounty09_wandsworth,
      uacounty09_westminster,
      uacounty09_barking_and_dagenham,
      uacounty09_barnet,
      uacounty09_bexley,
      uacounty09_brent,
      uacounty09_bromley,
      uacounty09_croydon,
      uacounty09_ealing,
      uacounty09_enfield,
      uacounty09_greenwich,
      uacounty09_harrow,
      uacounty09_havering,
      uacounty09_hillingdon,
      uacounty09_hounslow,
      uacounty09_kingston_upon_thames,
      uacounty09_merton,
      uacounty09_redbridge,
      uacounty09_richmond_upon_thames,
      uacounty09_sutton,
      uacounty09_waltham_forest,
      uacounty09_bracknell_forest,
      uacounty09_brighton_and_hove,
      uacounty09_isle_of_wight,
      uacounty09_medway,
      uacounty09_milton_keynes,
      uacounty09_portsmouth,
      uacounty09_reading,
      uacounty09_slough,
      uacounty09_southampton,
      uacounty09_west_berkshire,
      uacounty09_windsor_and_maidenhead,
      uacounty09_wokingham,
      uacounty09_buckinghamshire,
      uacounty09_east_sussex,
      uacounty09_hampshire,
      uacounty09_kent,
      uacounty09_oxfordshire,
      uacounty09_surrey,
      uacounty09_west_sussex,
      uacounty09_bath_and_north_east_somerset,
      uacounty09_bournemouth,
      uacounty09_bristol_city_of,
      uacounty09_cornwall,
      uacounty09_isles_of_scilly,
      uacounty09_north_somerset,
      uacounty09_plymouth,
      uacounty09_poole,
      uacounty09_south_gloucestershire,
      uacounty09_swindon,
      uacounty09_torbay,
      uacounty09_wiltshire,
      uacounty09_devon,
      uacounty09_dorset,
      uacounty09_gloucestershire,
      uacounty09_somerset,
      uacounty09_anglesey,
      uacounty09_gwynedd,
      uacounty09_conwy,
      uacounty09_denbighshire,
      uacounty09_flintshire,
      uacounty09_wrexham,
      uacounty09_powys,
      uacounty09_ceredigion,
      uacounty09_pembrokeshire,
      uacounty09_carmarthenshire,
      uacounty09_swansea,
      uacounty09_neath_port_talbot,
      uacounty09_bridgend,
      uacounty09_the_vale_of_glamorgan,
      uacounty09_cardiff,
      uacounty09_rhondda_cynon_taff,
      uacounty09_merthyr_tydfil,
      uacounty09_caerphilly,
      uacounty09_blaenau_gwent,
      uacounty09_torfaen,
      uacounty09_monmouthshire,
      uacounty09_newport,
      ualad09_darlington,
      ualad09_county_durham,
      ualad09_hartlepool,
      ualad09_middlesbrough,
      ualad09_northumberland,
      ualad09_redcar_and_cleveland,
      ualad09_stockton_on_tees,
      ualad09_gateshead,
      ualad09_newcastle_upon_tyne,
      ualad09_north_tyneside,
      ualad09_south_tyneside,
      ualad09_sunderland,
      ualad09_blackburn_with_darwen,
      ualad09_blackpool,
      ualad09_cheshire_east,
      ualad09_cheshire_west_and_chester,
      ualad09_halton,
      ualad09_warrington,
      ualad09_allerdale,
      ualad09_barrow_in_furness,
      ualad09_carlisle,
      ualad09_copeland,
      ualad09_eden,
      ualad09_south_lakeland,
      ualad09_bolton,
      ualad09_bury,
      ualad09_manchester,
      ualad09_oldham,
      ualad09_rochdale,
      ualad09_salford,
      ualad09_stockport,
      ualad09_tameside,
      ualad09_trafford,
      ualad09_wigan,
      ualad09_burnley,
      ualad09_chorley,
      ualad09_fylde,
      ualad09_hyndburn,
      ualad09_lancaster,
      ualad09_pendle,
      ualad09_preston,
      ualad09_ribble_valley,
      ualad09_rossendale,
      ualad09_south_ribble,
      ualad09_west_lancashire,
      ualad09_wyre,
      ualad09_knowsley,
      ualad09_liverpool,
      ualad09_sefton,
      ualad09_st_helens,
      ualad09_wirral,
      ualad09_east_riding_of_yorkshire,
      ualad09_kingston_upon_hull_city_of,
      ualad09_north_east_lincolnshire,
      ualad09_north_lincolnshire,
      ualad09_york,
      ualad09_craven,
      ualad09_hambleton,
      ualad09_harrogate,
      ualad09_richmondshire,
      ualad09_ryedale,
      ualad09_scarborough,
      ualad09_selby,
      ualad09_barnsley,
      ualad09_doncaster,
      ualad09_rotherham,
      ualad09_sheffield,
      ualad09_bradford,
      ualad09_calderdale,
      ualad09_kirklees,
      ualad09_leeds,
      ualad09_wakefield,
      ualad09_derby,
      ualad09_leicester,
      ualad09_nottingham,
      ualad09_rutland,
      ualad09_amber_valley,
      ualad09_bolsover,
      ualad09_chesterfield,
      ualad09_derbyshire_dales,
      ualad09_erewash,
      ualad09_high_peak,
      ualad09_north_east_derbyshire,
      ualad09_south_derbyshire,
      ualad09_blaby,
      ualad09_charnwood,
      ualad09_harborough,
      ualad09_hinckley_and_bosworth,
      ualad09_melton,
      ualad09_north_west_leicestershire,
      ualad09_oadby_and_wigston,
      ualad09_boston,
      ualad09_east_lindsey,
      ualad09_lincoln,
      ualad09_north_kesteven,
      ualad09_south_holland,
      ualad09_south_kesteven,
      ualad09_west_lindsey,
      ualad09_corby,
      ualad09_daventry,
      ualad09_east_northamptonshire,
      ualad09_kettering,
      ualad09_northampton,
      ualad09_south_northamptonshire,
      ualad09_wellingborough,
      ualad09_ashfield,
      ualad09_bassetlaw,
      ualad09_broxtowe,
      ualad09_gedling,
      ualad09_mansfield,
      ualad09_newark_and_sherwood,
      ualad09_rushcliffe,
      ualad09_herefordshire_county_of,
      ualad09_shropshire,
      ualad09_stoke_on_trent,
      ualad09_telford_and_wrekin,
      ualad09_cannock_chase,
      ualad09_east_staffordshire,
      ualad09_lichfield,
      ualad09_newcastle_under_lyme,
      ualad09_south_staffordshire,
      ualad09_stafford,
      ualad09_staffordshire_moorlands,
      ualad09_tamworth,
      ualad09_north_warwickshire,
      ualad09_nuneaton_and_bedworth,
      ualad09_rugby,
      ualad09_stratford_on_avon,
      ualad09_warwick,
      ualad09_birmingham,
      ualad09_coventry,
      ualad09_dudley,
      ualad09_sandwell,
      ualad09_solihull,
      ualad09_walsall,
      ualad09_wolverhampton,
      ualad09_bromsgrove,
      ualad09_malvern_hills,
      ualad09_redditch,
      ualad09_worcester,
      ualad09_wychavon,
      ualad09_wyre_forest,
      ualad09_bedford,
      ualad09_central_bedfordshire,
      ualad09_luton,
      ualad09_peterborough,
      ualad09_southend_on_sea,
      ualad09_thurrock,
      ualad09_cambridge,
      ualad09_east_cambridgeshire,
      ualad09_fenland,
      ualad09_huntingdonshire,
      ualad09_south_cambridgeshire,
      ualad09_basildon,
      ualad09_braintree,
      ualad09_brentwood,
      ualad09_castle_point,
      ualad09_chelmsford,
      ualad09_colchester,
      ualad09_epping_forest,
      ualad09_harlow,
      ualad09_maldon,
      ualad09_rochford,
      ualad09_tendring,
      ualad09_uttlesford,
      ualad09_broxbourne,
      ualad09_dacorum,
      ualad09_east_hertfordshire,
      ualad09_hertsmere,
      ualad09_north_hertfordshire,
      ualad09_st_albans,
      ualad09_stevenage,
      ualad09_three_rivers,
      ualad09_watford,
      ualad09_welwyn_hatfield,
      ualad09_breckland,
      ualad09_broadland,
      ualad09_great_yarmouth,
      ualad09_kings_lynn_and_west_norfolk,
      ualad09_north_norfolk,
      ualad09_norwich,
      ualad09_south_norfolk,
      ualad09_babergh,
      ualad09_forest_heath,
      ualad09_ipswich,
      ualad09_mid_suffolk,
      ualad09_st_edmundsbury,
      ualad09_suffolk_coastal,
      ualad09_waveney,
      ualad09_camden,
      ualad09_city_of_london,
      ualad09_hackney,
      ualad09_hammersmith_and_fulham,
      ualad09_haringey,
      ualad09_islington,
      ualad09_kensington_and_chelsea,
      ualad09_lambeth,
      ualad09_lewisham,
      ualad09_newham,
      ualad09_southwark,
      ualad09_tower_hamlets,
      ualad09_wandsworth,
      ualad09_westminster,
      ualad09_barking_and_dagenham,
      ualad09_barnet,
      ualad09_bexley,
      ualad09_brent,
      ualad09_bromley,
      ualad09_croydon,
      ualad09_ealing,
      ualad09_enfield,
      ualad09_greenwich,
      ualad09_harrow,
      ualad09_havering,
      ualad09_hillingdon,
      ualad09_hounslow,
      ualad09_kingston_upon_thames,
      ualad09_merton,
      ualad09_redbridge,
      ualad09_richmond_upon_thames,
      ualad09_sutton,
      ualad09_waltham_forest,
      ualad09_bracknell_forest,
      ualad09_brighton_and_hove,
      ualad09_isle_of_wight,
      ualad09_medway,
      ualad09_milton_keynes,
      ualad09_portsmouth,
      ualad09_reading,
      ualad09_slough,
      ualad09_southampton,
      ualad09_west_berkshire,
      ualad09_windsor_and_maidenhead,
      ualad09_wokingham,
      ualad09_aylesbury_vale,
      ualad09_chiltern,
      ualad09_south_bucks,
      ualad09_wycombe,
      ualad09_eastbourne,
      ualad09_hastings,
      ualad09_lewes,
      ualad09_rother,
      ualad09_wealden,
      ualad09_basingstoke_and_deane,
      ualad09_east_hampshire,
      ualad09_eastleigh,
      ualad09_fareham,
      ualad09_gosport,
      ualad09_hart,
      ualad09_havant,
      ualad09_new_forest,
      ualad09_rushmoor,
      ualad09_test_valley,
      ualad09_winchester,
      ualad09_ashford,
      ualad09_canterbury,
      ualad09_dartford,
      ualad09_dover,
      ualad09_gravesham,
      ualad09_maidstone,
      ualad09_sevenoaks,
      ualad09_shepway,
      ualad09_swale,
      ualad09_thanet,
      ualad09_tonbridge_and_malling,
      ualad09_tunbridge_wells,
      ualad09_cherwell,
      ualad09_oxford,
      ualad09_south_oxfordshire,
      ualad09_vale_of_white_horse,
      ualad09_west_oxfordshire,
      ualad09_elmbridge,
      ualad09_epsom_and_ewell,
      ualad09_guildford,
      ualad09_mole_valley,
      ualad09_reigate_and_banstead,
      ualad09_runnymede,
      ualad09_spelthorne,
      ualad09_surrey_heath,
      ualad09_tandridge,
      ualad09_waverley,
      ualad09_woking,
      ualad09_adur,
      ualad09_arun,
      ualad09_chichester,
      ualad09_crawley,
      ualad09_horsham,
      ualad09_mid_sussex,
      ualad09_worthing,
      ualad09_bath_and_north_east_somerset,
      ualad09_bournemouth,
      ualad09_bristol_city_of,
      ualad09_cornwall,
      ualad09_isles_of_scilly,
      ualad09_north_somerset,
      ualad09_plymouth,
      ualad09_poole,
      ualad09_south_gloucestershire,
      ualad09_swindon,
      ualad09_torbay,
      ualad09_wiltshire,
      ualad09_east_devon,
      ualad09_exeter,
      ualad09_mid_devon,
      ualad09_north_devon,
      ualad09_south_hams,
      ualad09_teignbridge,
      ualad09_torridge,
      ualad09_west_devon,
      ualad09_christchurch,
      ualad09_east_dorset,
      ualad09_north_dorset,
      ualad09_purbeck,
      ualad09_west_dorset,
      ualad09_weymouth_and_portland,
      ualad09_cheltenham,
      ualad09_cotswold,
      ualad09_forest_of_dean,
      ualad09_gloucester,
      ualad09_stroud,
      ualad09_tewkesbury,
      ualad09_mendip,
      ualad09_sedgemoor,
      ualad09_south_somerset,
      ualad09_taunton_deane,
      ualad09_west_somerset,
      ualad09_anglesey,
      ualad09_gwynedd,
      ualad09_conwy,
      ualad09_denbighshire,
      ualad09_flintshire,
      ualad09_wrexham,
      ualad09_powys,
      ualad09_ceredigion,
      ualad09_pembrokeshire,
      ualad09_carmarthenshire,
      ualad09_swansea,
      ualad09_neath_port_talbot,
      ualad09_bridgend,
      ualad09_the_vale_of_glamorgan,
      ualad09_cardiff,
      ualad09_rhondda_cynon_taff,
      ualad09_merthyr_tydfil,
      ualad09_caerphilly,
      ualad09_blaenau_gwent,
      ualad09_torfaen,
      ualad09_monmouthshire,
      ualad09_newport );

   type Government_Regions is (  
         north_east,
         north_west,
         yorkshire_and_the_humber,
         east_midlands,
         west_midlands,
         east,
         london,
         south_east,
         south_west,
         wales,
         scotland,
         northern_ireland );
   subtype Regions_England_And_Wales is Government_Regions range north_east .. wales; 
   subtype Regions_England is Government_Regions range north_east .. south_west; 
         
   subtype District_Or_Unitary_Authorities is Local_Authorities range ualad09_darlington .. ualad09_newport;   
   subtype County_Or_Unitary_Authorities is Local_Authorities range uacounty09_darlington ..  uacounty09_newport;
   
   subtype Districts_North_East is District_Or_Unitary_Authorities range ualad09_darlington .. ualad09_sunderland;
   subtype Districts_North_West is District_Or_Unitary_Authorities range ualad09_blackburn_with_darwen .. ualad09_wirral;
   subtype Districts_Yorkshire_and_The_Humber is District_Or_Unitary_Authorities range ualad09_east_riding_of_yorkshire .. ualad09_wakefield;
   subtype Districts_East_Midlands is District_Or_Unitary_Authorities range ualad09_derby .. ualad09_rushcliffe;
   subtype Districts_West_Midlands is District_Or_Unitary_Authorities range ualad09_herefordshire_county_of .. ualad09_wyre_forest;
   subtype Districts_East is District_Or_Unitary_Authorities range ualad09_bedford .. ualad09_waveney;
   subtype Districts_London is District_Or_Unitary_Authorities range ualad09_camden .. ualad09_waltham_forest;
   subtype Districts_South_East is District_Or_Unitary_Authorities range ualad09_bracknell_forest .. ualad09_worthing;
   subtype Districts_South_West is District_Or_Unitary_Authorities range ualad09_bath_and_north_east_somerset .. ualad09_west_somerset;
   subtype Districts_England is District_Or_Unitary_Authorities range ualad09_darlington .. ualad09_west_somerset;
   subtype Districts_Wales is District_Or_Unitary_Authorities range ualad09_anglesey .. ualad09_newport ;
   
   function FRS_Government_Region_Of_LA( la : District_Or_Unitary_Authorities ) return Government_Regions;
   
   function Map_FRS_Government_Region( frs : Integer ) return Government_Regions;
   
   type Weight_Targets is (
      genders_all_usual_residents,
      genders_males,
      genders_females,
      genders_lives_in_a_household,
      genders_lives_in_a_communal_establishment,
      age_ranges_all_categories_age,
      age_ranges_age_under_1,
      age_ranges_age_1,
      age_ranges_age_2,
      age_ranges_age_3,
      age_ranges_age_4,
      age_ranges_age_5,
      age_ranges_age_6,
      age_ranges_age_7,
      age_ranges_age_8,
      age_ranges_age_9,
      age_ranges_age_10,
      age_ranges_age_11,
      age_ranges_age_12,
      age_ranges_age_13,
      age_ranges_age_14,
      age_ranges_age_15,
      age_ranges_age_16,
      age_ranges_age_17,
      age_ranges_age_18,
      age_ranges_age_19,
      age_ranges_age_20,
      age_ranges_age_21,
      age_ranges_age_22,
      age_ranges_age_23,
      age_ranges_age_24,
      age_ranges_age_25,
      age_ranges_age_26,
      age_ranges_age_27,
      age_ranges_age_28,
      age_ranges_age_29,
      age_ranges_age_30,
      age_ranges_age_31,
      age_ranges_age_32,
      age_ranges_age_33,
      age_ranges_age_34,
      age_ranges_age_35,
      age_ranges_age_36,
      age_ranges_age_37,
      age_ranges_age_38,
      age_ranges_age_39,
      age_ranges_age_40,
      age_ranges_age_41,
      age_ranges_age_42,
      age_ranges_age_43,
      age_ranges_age_44,
      age_ranges_age_45,
      age_ranges_age_46,
      age_ranges_age_47,
      age_ranges_age_48,
      age_ranges_age_49,
      age_ranges_age_50,
      age_ranges_age_51,
      age_ranges_age_52,
      age_ranges_age_53,
      age_ranges_age_54,
      age_ranges_age_55,
      age_ranges_age_56,
      age_ranges_age_57,
      age_ranges_age_58,
      age_ranges_age_59,
      age_ranges_age_60,
      age_ranges_age_61,
      age_ranges_age_62,
      age_ranges_age_63,
      age_ranges_age_64,
      age_ranges_age_65,
      age_ranges_age_66,
      age_ranges_age_67,
      age_ranges_age_68,
      age_ranges_age_69,
      age_ranges_age_70,
      age_ranges_age_71,
      age_ranges_age_72,
      age_ranges_age_73,
      age_ranges_age_74,
      age_ranges_age_75,
      age_ranges_age_76,
      age_ranges_age_77,
      age_ranges_age_78,
      age_ranges_age_79,
      age_ranges_age_80,
      age_ranges_age_81,
      age_ranges_age_82,
      age_ranges_age_83,
      age_ranges_age_84,
      age_ranges_age_85,
      age_ranges_age_86,
      age_ranges_age_87,
      age_ranges_age_88,
      age_ranges_age_89,
      age_ranges_age_90,
      age_ranges_age_91,
      age_ranges_age_92,
      age_ranges_age_93,
      age_ranges_age_94,
      age_ranges_age_95,
      age_ranges_age_96,
      age_ranges_age_97,
      age_ranges_age_98,
      age_ranges_age_99,
      age_ranges_age_100_and_over,
      accomodation_type_all_categories_accommodation_type,
      accomodation_type_unshared_dwelling_total,
      accomodation_type_unshared_dwelling_whole_house_or_bungalow_total,
      accomodation_type_unshared_dwelling_whole_house_or_bungalow_detached,
      accomodation_type_unshared_dwelling_whole_house_or_bungalow_semi_detached,
      accomodation_type_unshared_dwelling_whole_house_or_bungalow_terraced_including_end_terrace,
      accomodation_type_unshared_dwelling_flat_maisonette_or_apartment_total,
      accomodation_type_unshared_dwelling_flat_maisonette_or_apartment_purpose_built_block_of_flats_or_tenement,
      accomodation_type_unshared_dwelling_flat_maisonette_or_apartment_part_of_a_converted_or_shared_house_including_bed_sits,
      accomodation_type_unshared_dwelling_flat_maisonette_or_apartment_in_commercial_building,
      accomodation_type_unshared_dwelling_caravan_or_other_mobile_or_temporary_structure,
      accomodation_type_shared_dwelling,
      economic_activity_all_categories_economic_activity,
      economic_activity_economically_active_total,
      economic_activity_economically_active_employee_part_time,
      economic_activity_economically_active_employee_full_time,
      economic_activity_economically_active_self_employed_with_employees_part_time,
      economic_activity_economically_active_self_employed_with_employees_full_time,
      economic_activity_economically_active_self_employed_without_employees_part_time,
      economic_activity_economically_active_self_employed_without_employees_full_time,
      economic_activity_economically_active_unemployed,
      economic_activity_economically_active_full_time_student,
      economic_activity_economically_inactive_total,
      economic_activity_economically_inactive_retired,
      economic_activity_economically_inactive_student_including_full_time_students,
      economic_activity_economically_inactive_looking_after_home_or_family,
      economic_activity_economically_inactive_long_term_sick_or_disabled,
      economic_activity_economically_inactive_other,
      ethnic_group_all_categories_ethnic_group,
      ethnic_group_white,
      ethnic_group_white_english_welsh_scottish_northern_irish_british,
      ethnic_group_white_irish,
      ethnic_group_white_gypsy_or_irish_traveller,
      ethnic_group_white_other_white,
      ethnic_group_mixed,
      ethnic_group_mixed_multiple_ethnic_group_white_and_black_caribbean,
      ethnic_group_mixed_multiple_ethnic_group_white_and_black_african,
      ethnic_group_mixed_multiple_ethnic_group_white_and_asian,
      ethnic_group_mixed_multiple_ethnic_group_other_mixed,
      ethnic_group_asian,
      ethnic_group_asian_asian_british_indian,
      ethnic_group_asian_asian_british_pakistani,
      ethnic_group_asian_asian_british_bangladeshi,
      ethnic_group_asian_asian_british_chinese,
      ethnic_group_asian_asian_british_other_asian,
      ethnic_group_black,
      ethnic_group_black_african_caribbean_black_british_african,
      ethnic_group_black_african_caribbean_black_british_caribbean,
      ethnic_group_black_african_caribbean_black_british_other_black,
      ethnic_group_other,
      ethnic_group_other_ethnic_group_arab,
      ethnic_group_other_ethnic_group_any_other_ethnic_group,
      household_composition_all_categories_household_composition,
      household_composition_one_person_household_total,
      household_composition_one_person_household_aged_65_and_over,
      household_composition_one_person_household_other,
      household_composition_one_family_only_total,
      household_composition_one_family_only_all_aged_65_and_over,
      household_composition_one_family_only_married_couple_total,
      household_composition_one_family_only_married_couple_no_children,
      household_composition_one_family_only_married_couple_one_dependent_child,
      household_composition_one_family_only_married_couple_two_or_more_dependent_children,
      household_composition_one_family_only_married_couple_all_children_non_dependent,
      household_composition_one_family_only_same_sex_civil_partnership_couple_total,
      household_composition_one_family_only_same_sex_civil_partnership_couple_no_children,
      household_composition_one_family_only_same_sex_civil_partnership_couple_one_dependent_child,
      household_composition_one_family_only_same_sex_civil_partnership_couple_two_or_more_dependent_children,
      household_composition_one_family_only_same_sex_civil_partnership_couple_all_children_non_dependent,
      household_composition_one_family_only_cohabiting_couple_total,
      household_composition_one_family_only_cohabiting_couple_no_children,
      household_composition_one_family_only_cohabiting_couple_one_dependent_child,
      household_composition_one_family_only_cohabiting_couple_two_or_more_dependent_children,
      household_composition_one_family_only_cohabiting_couple_all_children_non_dependent,
      household_composition_one_family_only_lone_parent_total,
      household_composition_one_family_only_lone_parent_one_dependent_child,
      household_composition_one_family_only_lone_parent_two_or_more_dependent_children,
      household_composition_one_family_only_lone_parent_all_children_non_dependent,
      household_composition_other_household_types_total,
      household_composition_other_household_types_with_one_dependent_child,
      household_composition_other_household_types_with_two_or_more_dependent_children,
      household_composition_other_household_types_all_full_time_students,
      household_composition_other_household_types_all_aged_65_and_over,
      household_composition_other_household_types_other,
      number_of_rooms_all_categories_number_of_rooms,
      number_of_rooms_1_room,
      number_of_rooms_2_rooms,
      number_of_rooms_3_rooms,
      number_of_rooms_4_rooms,
      number_of_rooms_5_rooms,
      number_of_rooms_6_rooms,
      number_of_rooms_7_rooms,
      number_of_rooms_8_rooms,
      number_of_rooms_9_or_more_rooms,
      residence_type_all_categories_residence_type,
      residence_type_lives_in_a_household,
      residence_type_lives_in_a_communal_establishment,
      residence_type_communal_establishments_with_persons_sleeping_rough_identified,
      tenure_type_all_categories_tenure,
      tenure_type_owned_total,
      tenure_type_owned_owned_outright,
      tenure_type_owned_owned_with_a_mortgage_or_loan,
      tenure_type_shared_ownership_part_owned_and_part_rented,
      tenure_type_social_rented_total,
      tenure_type_social_rented_rented_from_council_local_authority,
      tenure_type_social_rented_other_social_rented,
      tenure_type_private_rented_total,
      tenure_type_private_rented_private_landlord_or_letting_agency,
      tenure_type_private_rented_employer_of_a_household_member,
      tenure_type_private_rented_relative_or_friend_of_household_member,
      tenure_type_private_rented_other,
      tenure_type_living_rent_free,
      occupation_all_categories_occupation,
      occupation_1_managers_directors_and_senior_officials,
      occupation_2_professional_occupations,
      occupation_3_associate_professional_and_technical_occupations,
      occupation_4_administrative_and_secretarial_occupations,
      occupation_5_skilled_trades_occupations,
      occupation_6_caring_leisure_and_other_service_occupations,
      occupation_7_sales_and_customer_service_occupations,
      occupation_8_process_plant_and_machine_operatives,
      occupation_9_elementary_occupations );
      
   type Weighting_Sample_Type is ( whole_sample, england_and_wales, england, government_region );
 
   type Reweighting_Targets is ( 
      age_u5, 
      age_5_10, 
      age_11_15, 
      age_16_24, 
      age_25_59, 
      age_60_64,
      age_65_74, 
      age_75_plus,
      gender_male,
      gender_female,
      ethnic_group_white,
      ethnic_group_mixed,
      ethnic_group_asian,
      ethnic_group_black,
      ethnic_group_other,
      tenure_la,
      tenure_other_social,
      tenure_private_rented,
      tenure_mortgaged,
      tenure_owned_outright,
      tenure_rent_free_or_other,
      rooms_1,
      rooms_2_3,
      rooms_4_5,
      rooms_6_plus,
      ilo_employed,
      ilo_unemployed,
      ilo_inactive,
      occupation_white_collar,
      occupation_blue_collar );
   subtype Reweighting_Targets_Age is Reweighting_Targets range age_u5 .. age_75_plus;
   subtype Reweighting_Targets_Gender is Reweighting_Targets range gender_male .. gender_female;
   subtype Reweighting_Targets_Ethnic is Reweighting_Targets range ethnic_group_white .. ethnic_group_other;
   subtype Reweighting_Targets_Tenure is Reweighting_Targets range tenure_la .. tenure_rent_free_or_other;
   subtype Reweighting_Targets_Rooms is Reweighting_Targets range rooms_1 .. rooms_6_plus;
   subtype Reweighting_Targets_EmpStat is Reweighting_Targets range ilo_employed .. ilo_inactive;
   subtype Reweighting_Targets_Occupation is Reweighting_Targets range occupation_white_collar .. occupation_blue_collar;
   
   procedure Read_Pointers( filename : String );
   
   procedure Make_And_Store_FRS_Datasets( outdir : String );
   
   procedure Create_Weights(
      frs_dir               : in String;
      output_dir            : in String;
      start_la              : in District_Or_Unitary_Authorities;
      end_la                : in District_Or_Unitary_Authorities;
      target_type           : in Weighting_Sample_Type;
      weighting_lower_bound : in Amount; 
      weighting_upper_bound : in Amount;
      weighting_function    : in Distance_Function_Type );
 
   Weighting_Exception : exception;
   
   function Header_String return String;
private       
   use Ada.Calendar;
   use Data_Constants;
   
   THIS_YEAR   : constant Data_Years := 2010;
   -- scotland and ireland
   subtype Compressed_Targets_Range is Positive range 1 .. Reweighting_Targets'Pos( Reweighting_Targets'Last ) + 1;
   type Row_Vector is array( Reweighting_Targets ) of Amount; 

   function Get_Target_Vector_For_LA( la : Local_Authorities ) return Row_Vector;
   
   function Get_Target_Household_Count(
      target_type  : Weighting_Sample_Type;
      which_region : Government_Regions;
      year         : Year_Number := THIS_YEAR ) return Natural;   
      
  function Map_Ethnic_Group( ieg : Integer ) return Reweighting_Targets_Ethnic;
  function Map_Household( hh : Raw_FRS.Raw_Household ) return Row_Vector;
  
      
end LA_Reweighter;
