--
-- created on 12-06-2013 by Mill
--
drop database if exists la_data;
create database la_data with encoding 'UTF-8';

\c la_data;


CREATE TABLE target_candidates( 
       id INTEGER not null,
       code VARCHAR(10) not null,
       edition INTEGER not null,
       frs_region INTEGER not null,
       hb_total DOUBLE PRECISION,
       hb_social_rented_sector DOUBLE PRECISION,
       hb_private_rented_sector DOUBLE PRECISION,
       hb_passported DOUBLE PRECISION,
       hb_non_passported DOUBLE PRECISION,
       ct_all DOUBLE PRECISION,
       ct_passported DOUBLE PRECISION,
       ct_non_passported DOUBLE PRECISION,
       genders_all_usual_residents DOUBLE PRECISION,
       genders_males DOUBLE PRECISION,
       genders_females DOUBLE PRECISION,
       genders_lives_in_a_household DOUBLE PRECISION,
       genders_lives_in_a_communal_establishment DOUBLE PRECISION,
       genders_schoolchild_or_student_non_term_time_address DOUBLE PRECISION,
       age_ranges_all_categories_age DOUBLE PRECISION,
       age_ranges_age_under_1 DOUBLE PRECISION,
       age_ranges_age_1 DOUBLE PRECISION,
       age_ranges_age_2 DOUBLE PRECISION,
       age_ranges_age_3 DOUBLE PRECISION,
       age_ranges_age_4 DOUBLE PRECISION,
       age_ranges_age_5 DOUBLE PRECISION,
       age_ranges_age_6 DOUBLE PRECISION,
       age_ranges_age_7 DOUBLE PRECISION,
       age_ranges_age_8 DOUBLE PRECISION,
       age_ranges_age_9 DOUBLE PRECISION,
       age_ranges_age_10 DOUBLE PRECISION,
       age_ranges_age_11 DOUBLE PRECISION,
       age_ranges_age_12 DOUBLE PRECISION,
       age_ranges_age_13 DOUBLE PRECISION,
       age_ranges_age_14 DOUBLE PRECISION,
       age_ranges_age_15 DOUBLE PRECISION,
       age_ranges_age_16 DOUBLE PRECISION,
       age_ranges_age_17 DOUBLE PRECISION,
       age_ranges_age_18 DOUBLE PRECISION,
       age_ranges_age_19 DOUBLE PRECISION,
       age_ranges_age_20 DOUBLE PRECISION,
       age_ranges_age_21 DOUBLE PRECISION,
       age_ranges_age_22 DOUBLE PRECISION,
       age_ranges_age_23 DOUBLE PRECISION,
       age_ranges_age_24 DOUBLE PRECISION,
       age_ranges_age_25 DOUBLE PRECISION,
       age_ranges_age_26 DOUBLE PRECISION,
       age_ranges_age_27 DOUBLE PRECISION,
       age_ranges_age_28 DOUBLE PRECISION,
       age_ranges_age_29 DOUBLE PRECISION,
       age_ranges_age_30 DOUBLE PRECISION,
       age_ranges_age_31 DOUBLE PRECISION,
       age_ranges_age_32 DOUBLE PRECISION,
       age_ranges_age_33 DOUBLE PRECISION,
       age_ranges_age_34 DOUBLE PRECISION,
       age_ranges_age_35 DOUBLE PRECISION,
       age_ranges_age_36 DOUBLE PRECISION,
       age_ranges_age_37 DOUBLE PRECISION,
       age_ranges_age_38 DOUBLE PRECISION,
       age_ranges_age_39 DOUBLE PRECISION,
       age_ranges_age_40 DOUBLE PRECISION,
       age_ranges_age_41 DOUBLE PRECISION,
       age_ranges_age_42 DOUBLE PRECISION,
       age_ranges_age_43 DOUBLE PRECISION,
       age_ranges_age_44 DOUBLE PRECISION,
       age_ranges_age_45 DOUBLE PRECISION,
       age_ranges_age_46 DOUBLE PRECISION,
       age_ranges_age_47 DOUBLE PRECISION,
       age_ranges_age_48 DOUBLE PRECISION,
       age_ranges_age_49 DOUBLE PRECISION,
       age_ranges_age_50 DOUBLE PRECISION,
       age_ranges_age_51 DOUBLE PRECISION,
       age_ranges_age_52 DOUBLE PRECISION,
       age_ranges_age_53 DOUBLE PRECISION,
       age_ranges_age_54 DOUBLE PRECISION,
       age_ranges_age_55 DOUBLE PRECISION,
       age_ranges_age_56 DOUBLE PRECISION,
       age_ranges_age_57 DOUBLE PRECISION,
       age_ranges_age_58 DOUBLE PRECISION,
       age_ranges_age_59 DOUBLE PRECISION,
       age_ranges_age_60 DOUBLE PRECISION,
       age_ranges_age_61 DOUBLE PRECISION,
       age_ranges_age_62 DOUBLE PRECISION,
       age_ranges_age_63 DOUBLE PRECISION,
       age_ranges_age_64 DOUBLE PRECISION,
       age_ranges_age_65 DOUBLE PRECISION,
       age_ranges_age_66 DOUBLE PRECISION,
       age_ranges_age_67 DOUBLE PRECISION,
       age_ranges_age_68 DOUBLE PRECISION,
       age_ranges_age_69 DOUBLE PRECISION,
       age_ranges_age_70 DOUBLE PRECISION,
       age_ranges_age_71 DOUBLE PRECISION,
       age_ranges_age_72 DOUBLE PRECISION,
       age_ranges_age_73 DOUBLE PRECISION,
       age_ranges_age_74 DOUBLE PRECISION,
       age_ranges_age_75 DOUBLE PRECISION,
       age_ranges_age_76 DOUBLE PRECISION,
       age_ranges_age_77 DOUBLE PRECISION,
       age_ranges_age_78 DOUBLE PRECISION,
       age_ranges_age_79 DOUBLE PRECISION,
       age_ranges_age_80 DOUBLE PRECISION,
       age_ranges_age_81 DOUBLE PRECISION,
       age_ranges_age_82 DOUBLE PRECISION,
       age_ranges_age_83 DOUBLE PRECISION,
       age_ranges_age_84 DOUBLE PRECISION,
       age_ranges_age_85 DOUBLE PRECISION,
       age_ranges_age_86 DOUBLE PRECISION,
       age_ranges_age_87 DOUBLE PRECISION,
       age_ranges_age_88 DOUBLE PRECISION,
       age_ranges_age_89 DOUBLE PRECISION,
       age_ranges_age_90 DOUBLE PRECISION,
       age_ranges_age_91 DOUBLE PRECISION,
       age_ranges_age_92 DOUBLE PRECISION,
       age_ranges_age_93 DOUBLE PRECISION,
       age_ranges_age_94 DOUBLE PRECISION,
       age_ranges_age_95 DOUBLE PRECISION,
       age_ranges_age_96 DOUBLE PRECISION,
       age_ranges_age_97 DOUBLE PRECISION,
       age_ranges_age_98 DOUBLE PRECISION,
       age_ranges_age_99 DOUBLE PRECISION,
       age_ranges_age_100_and_over DOUBLE PRECISION,
       accom_all_categories_accommodation_type DOUBLE PRECISION,
       accom_unshared_total DOUBLE PRECISION,
       accom_unshared_whole_house_or_bungalow_total DOUBLE PRECISION,
       accom_unshared_whole_house_or_bungalow_detached DOUBLE PRECISION,
       accom_unshared_whole_house_or_bungalow_semi_detached DOUBLE PRECISION,
       accom_unshared_whole_house_or_bungalow_terraced DOUBLE PRECISION,
       accom_unshared_flat_maisonette_or_apartment_total DOUBLE PRECISION,
       accom_unshared_flat_etc_purpose_built_flats_or_tenement DOUBLE PRECISION,
       accom_unshared_flat_etc_part_of_a_converted_or_shared_house DOUBLE PRECISION,
       accom_unshared_flat_etc_in_commercial_building DOUBLE PRECISION,
       accom_unshared_caravan_etc DOUBLE PRECISION,
       accom_shared DOUBLE PRECISION,
       ec_act_all_categories_economic_activity DOUBLE PRECISION,
       ec_act_active_total DOUBLE PRECISION,
       ec_act_active_employee_part_time DOUBLE PRECISION,
       ec_act_active_employee_full_time DOUBLE PRECISION,
       ec_act_active_self_employed_with_employees_part_time DOUBLE PRECISION,
       ec_act_active_self_employed_with_employees_full_time DOUBLE PRECISION,
       ec_act_active_self_employed_without_employees_part_time DOUBLE PRECISION,
       ec_act_active_self_employed_without_employees_full_time DOUBLE PRECISION,
       ec_act_active_unemployed DOUBLE PRECISION,
       ec_act_active_full_time_student DOUBLE PRECISION,
       ec_act_inactive_total DOUBLE PRECISION,
       ec_act_inactive_retired DOUBLE PRECISION,
       ec_act_inactive_student_including_full_time_students DOUBLE PRECISION,
       ec_act_inactive_looking_after_home_or_family DOUBLE PRECISION,
       ec_act_inactive_long_term_sick_or_disabled DOUBLE PRECISION,
       ec_act_inactive_other DOUBLE PRECISION,
       ethgrp_all_categories_ethnic_group DOUBLE PRECISION,
       ethgrp_white DOUBLE PRECISION,
       ethgrp_white_english_welsh_scottish_northern_irish_british DOUBLE PRECISION,
       ethgrp_white_irish DOUBLE PRECISION,
       ethgrp_white_gypsy_or_irish_traveller DOUBLE PRECISION,
       ethgrp_white_other_white DOUBLE PRECISION,
       ethgrp_mixed DOUBLE PRECISION,
       ethgrp_mixed_multiple_ethnic_group_white_and_black_caribbean DOUBLE PRECISION,
       ethgrp_mixed_multiple_ethnic_group_white_and_black_african DOUBLE PRECISION,
       ethgrp_mixed_multiple_ethnic_group_white_and_asian DOUBLE PRECISION,
       ethgrp_mixed_multiple_ethnic_group_other_mixed DOUBLE PRECISION,
       ethgrp_asian DOUBLE PRECISION,
       ethgrp_asian_asian_british_indian DOUBLE PRECISION,
       ethgrp_asian_asian_british_pakistani DOUBLE PRECISION,
       ethgrp_asian_asian_british_bangladeshi DOUBLE PRECISION,
       ethgrp_asian_asian_british_chinese DOUBLE PRECISION,
       ethgrp_asian_asian_british_other_asian DOUBLE PRECISION,
       ethgrp_black DOUBLE PRECISION,
       ethgrp_black_african_caribbean_black_british_african DOUBLE PRECISION,
       ethgrp_black_african_caribbean_black_british_caribbean DOUBLE PRECISION,
       ethgrp_black_african_caribbean_black_british_other_black DOUBLE PRECISION,
       ethgrp_other DOUBLE PRECISION,
       ethgrp_other_ethnic_group_arab DOUBLE PRECISION,
       ethgrp_other_ethnic_group_any_other_ethnic_group DOUBLE PRECISION,
       hcomp_all_categories_household_composition DOUBLE PRECISION,
       hcomp_one_person_household_total DOUBLE PRECISION,
       hcomp_one_person_household_aged_65_and_over DOUBLE PRECISION,
       hcomp_one_person_household_other DOUBLE PRECISION,
       hcomp_one_family_only_total DOUBLE PRECISION,
       hcomp_one_family_only_all_aged_65_and_over DOUBLE PRECISION,
       hcomp_one_family_only_married_cple_total DOUBLE PRECISION,
       hcomp_one_family_only_married_cple_no_kids DOUBLE PRECISION,
       hcomp_one_family_only_married_cple_one_dep_child DOUBLE PRECISION,
       hcomp_one_family_only_married_cple_two_or_more_dep_kids DOUBLE PRECISION,
       hcomp_one_family_only_married_cple_all_kids_non_dep DOUBLE PRECISION,
       hcomp_one_family_only_same_sex_civ_part_cple_total DOUBLE PRECISION,
       hcomp_one_family_only_same_sex_civ_part_cple_no_kids DOUBLE PRECISION,
       hcomp_same_sex_civ_part_cple_one_dep_child DOUBLE PRECISION,
       hcomp_same_sex_civ_part_cple_two_plus_dep_kids DOUBLE PRECISION,
       hcomp_one_family_only_same_sex_civ_part_cple_all_kids_non_dep DOUBLE PRECISION,
       hcomp_one_family_only_cohabiting_cple_total DOUBLE PRECISION,
       hcomp_one_family_only_cohabiting_cple_no_kids DOUBLE PRECISION,
       hcomp_one_family_only_cohabiting_cple_one_dep_child DOUBLE PRECISION,
       hcomp_one_family_only_cohabiting_cple_two_or_more_dep_kids DOUBLE PRECISION,
       hcomp_one_family_only_cohabiting_cple_all_kids_non_dep DOUBLE PRECISION,
       hcomp_one_family_only_lone_parent_total DOUBLE PRECISION,
       hcomp_one_family_only_lone_parent_one_dep_child DOUBLE PRECISION,
       hcomp_one_family_only_lone_parent_two_or_more_dep_kids DOUBLE PRECISION,
       hcomp_one_family_only_lone_parent_all_kids_non_dep DOUBLE PRECISION,
       hcomp_other_total DOUBLE PRECISION,
       hcomp_other_with_one_dep_child DOUBLE PRECISION,
       hcomp_other_with_two_or_more_dep_kids DOUBLE PRECISION,
       hcomp_other_all_full_time_students DOUBLE PRECISION,
       hcomp_other_all_aged_65_and_over DOUBLE PRECISION,
       hcomp_other_other DOUBLE PRECISION,
       number_of_rooms_all_categories_number_of_rooms DOUBLE PRECISION,
       number_of_rooms_1_room DOUBLE PRECISION,
       number_of_rooms_2_rooms DOUBLE PRECISION,
       number_of_rooms_3_rooms DOUBLE PRECISION,
       number_of_rooms_4_rooms DOUBLE PRECISION,
       number_of_rooms_5_rooms DOUBLE PRECISION,
       number_of_rooms_6_rooms DOUBLE PRECISION,
       number_of_rooms_7_rooms DOUBLE PRECISION,
       number_of_rooms_8_rooms DOUBLE PRECISION,
       number_of_rooms_9_or_more_rooms DOUBLE PRECISION,
       residence_all_categories_residence_type DOUBLE PRECISION,
       residence_lives_in_a_household DOUBLE PRECISION,
       residence_lives_in_a_communal_establishment DOUBLE PRECISION,
       residence_communal_establishments_with_persons_sleeping_rough DOUBLE PRECISION,
       tenure_all_categories_tenure DOUBLE PRECISION,
       tenure_owned_total DOUBLE PRECISION,
       tenure_owned_owned_outright DOUBLE PRECISION,
       tenure_owned_owned_with_a_mortgage_or_loan DOUBLE PRECISION,
       tenure_shared_ownership_part_owned_and_part_rented DOUBLE PRECISION,
       tenure_social_rented_total DOUBLE PRECISION,
       tenure_social_rented_rented_from_council_local_authority DOUBLE PRECISION,
       tenure_social_rented_other_social_rented DOUBLE PRECISION,
       tenure_private_rented_total DOUBLE PRECISION,
       tenure_private_rented_private_landlord_or_letting_agency DOUBLE PRECISION,
       tenure_private_rented_employer_of_a_household_member DOUBLE PRECISION,
       tenure_private_rented_relative_or_friend_of_household DOUBLE PRECISION,
       tenure_private_rented_other DOUBLE PRECISION,
       tenure_living_rent_free DOUBLE PRECISION,
       occupation_all_categories_occupation DOUBLE PRECISION,
       occupation_1_managers_directors_and_senior_officials DOUBLE PRECISION,
       occupation_2_professional_occupations DOUBLE PRECISION,
       occupation_3_associate_professional_and_technical_occupations DOUBLE PRECISION,
       occupation_4_administrative_and_secretarial_occupations DOUBLE PRECISION,
       occupation_5_skilled_trades_occupations DOUBLE PRECISION,
       occupation_6_caring_leisure_and_other_service_occupations DOUBLE PRECISION,
       occupation_7_sales_and_customer_service_occupations DOUBLE PRECISION,
       occupation_8_process_plant_and_machine_operatives DOUBLE PRECISION,
       occupation_9_elementary_occupations DOUBLE PRECISION,
       income_support_people_claiming_benefit DOUBLE PRECISION,
       income_support_average_weekly_payment DOUBLE PRECISION,
       jsa_total DOUBLE PRECISION,
       pension_credits_number_of_claimants DOUBLE PRECISION,
       pension_credits_number_of_beneficiaries DOUBLE PRECISION,
       pension_credits_average_weekly_payment DOUBLE PRECISION,
       out_of_work_families DOUBLE PRECISION,
       out_of_work_children DOUBLE PRECISION,
       wtc_and_ctc_families DOUBLE PRECISION,
       wtc_and_ctc_children DOUBLE PRECISION,
       ctc_only_families DOUBLE PRECISION,
       ctc_only_children DOUBLE PRECISION,
       childcare_element DOUBLE PRECISION,
       credits_no_children DOUBLE PRECISION,
       credits_total_families DOUBLE PRECISION,
       PRIMARY KEY( id, code, edition )
);

CREATE TABLE las( 
       code VARCHAR(10) not null,
       name VARCHAR(60),
       PRIMARY KEY( code )
);

CREATE TABLE country( 
       name VARCHAR(30) not null,
       PRIMARY KEY( name )
);

CREATE TABLE government_region( 
       name VARCHAR(30) not null,
       frs_region_code INTEGER not null,
       PRIMARY KEY( frs_region_code )
);
CREATE UNIQUE INDEX uniq_government_region_name ON government_region( name );

CREATE TABLE las_in_region( 
       lacode VARCHAR(10) not null,
       region VARCHAR(30),
       frs_region_code INTEGER not null,
       PRIMARY KEY( lacode, frs_region_code ),
       CONSTRAINT las_in_region_FK_0 FOREIGN KEY( lacode) references las( code ) on delete cascade on update cascade,
       CONSTRAINT las_in_region_FK_1 FOREIGN KEY( frs_region_code) references government_region( frs_region_code ) on delete cascade on update cascade,
       CONSTRAINT las_in_region_FK_2 FOREIGN KEY( region) references government_region( name ) on delete cascade on update cascade
);

CREATE TABLE regions_in_country( 
       country_name VARCHAR(30) not null,
       region_name VARCHAR(30),
       frs_region_code INTEGER not null,
       PRIMARY KEY( country_name, frs_region_code ),
       CONSTRAINT regions_in_country_FK_0 FOREIGN KEY( frs_region_code) references government_region( frs_region_code ) on delete cascade on update cascade,
       CONSTRAINT regions_in_country_FK_1 FOREIGN KEY( country_name) references country( name ) on delete cascade on update cascade
);

